-- Agregar columnas de dirección a la tabla users
ALTER TABLE users ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS address_ref TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS street_number TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS lat DOUBLE PRECISION;
ALTER TABLE users ADD COLUMN IF NOT EXISTS lng DOUBLE PRECISION; 